version: '2.1'

services:
  example-node-server:
    image: example-node-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ## set your startup file hvolu
    command: npm run dev
volumes:  
  node_modules:
    driver: local
